import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Mona_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar, { Navlink } from "@/components/navbar";
import { getAuthUser } from "@/features/auth/auth-utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const popin = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--popin",
});

const mona = Mona_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--mona",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authUser = await getAuthUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar>
          <Navlink href={"/"}>Home</Navlink>
          {authUser?.role === "admin" && (
            <>
              <Navlink href={"/dashboard"}>Dashboard</Navlink>
            </>
          )}
          <Navlink href={"/products"}>Products</Navlink>
          <Navlink href={"/users"}>Users</Navlink>
          <Navlink href={"/sales"}>Sales</Navlink>
        </Navbar>
        <main className={cn(`container mx-auto py-4`, popin.className)}>
          {children}
        </main>
      </body>
    </html>
  );
}
